-- Jalankan di phpMyAdmin setelah memilih database ppdb_db.
-- Tabel ini sesuai dengan formulir PPDB baru dan tetap menyediakan
-- kolom yang dibutuhkan dashboard/admin project lama.

CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,

    nama_sekolah_asal VARCHAR(150),
    status_sekolah_asal VARCHAR(20),
    npsn_nsm_asal VARCHAR(30),
    alamat_sekolah_asal TEXT,

    nama VARCHAR(150),
    nisn VARCHAR(20),
    nik VARCHAR(20),
    tempat_lahir VARCHAR(100),
    tanggal_lahir DATE,
    jk VARCHAR(20),
    jumlah_saudara INT,
    anak_ke INT,
    cita_cita VARCHAR(100),
    hobi VARCHAR(100),
    telepon VARCHAR(30),
    email VARCHAR(150),
    pembiaya_sekolah VARCHAR(100),
    pra_sekolah VARCHAR(50),
    imunisasi VARCHAR(50),
    no_kk VARCHAR(20),
    nama_kepala_keluarga VARCHAR(150),

    nama_ayah VARCHAR(150),
    status_ayah VARCHAR(30),
    nik_ayah VARCHAR(20),
    tanggal_lahir_ayah DATE,
    pendidikan_ayah VARCHAR(80),
    pekerjaan_ayah VARCHAR(150),
    penghasilan_ayah VARCHAR(100),
    hp_ayah VARCHAR(30),

    nama_ibu VARCHAR(150),
    status_ibu VARCHAR(30),
    nik_ibu VARCHAR(20),
    tanggal_lahir_ibu DATE,
    pendidikan_ibu VARCHAR(80),
    pekerjaan_ibu VARCHAR(150),
    penghasilan_ibu VARCHAR(100),
    hp_ibu VARCHAR(30),

    kepemilikan_rumah_ayah VARCHAR(100),
    provinsi_ayah VARCHAR(100),
    kabupaten_ayah VARCHAR(100),
    kecamatan_ayah VARCHAR(100),
    kelurahan_ayah VARCHAR(100),
    rt_ayah VARCHAR(10),
    rw_ayah VARCHAR(10),
    jalan_ayah TEXT,
    kode_pos_ayah VARCHAR(10),

    alamat_ibu_status VARCHAR(40),
    kepemilikan_rumah_ibu VARCHAR(100),
    provinsi_ibu VARCHAR(100),
    kabupaten_ibu VARCHAR(100),
    kecamatan_ibu VARCHAR(100),
    kelurahan_ibu VARCHAR(100),
    rt_ibu VARCHAR(10),
    rw_ibu VARCHAR(10),
    jalan_ibu TEXT,
    kode_pos_ibu VARCHAR(10),

    domisili_murid VARCHAR(100),
    transportasi VARCHAR(100),
    jarak_rumah VARCHAR(100),
    waktu_tempuh VARCHAR(100),
    kebutuhan_khusus VARCHAR(200),
    kebutuhan_disabilitas VARCHAR(100),

    status_wali VARCHAR(100),
    nama_wali VARCHAR(150),
    hp_wali VARCHAR(30),
    tinggal_bersama VARCHAR(100),
    alamat_wali TEXT,

    status VARCHAR(40) DEFAULT 'Menunggu Verifikasi',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_nisn (nisn),
    INDEX idx_nik (nik),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
